// flow-typed signature: 7a1ed78fbd5a4b42798e48b63ee9bb20
// flow-typed version: <<STUB>>/postcss-icss-values_v^2.0.1/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-icss-values'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-icss-values' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-icss-values/lib/icss' {
  declare module.exports: any;
}

declare module 'postcss-icss-values/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-icss-values/lib/icss.js' {
  declare module.exports: $Exports<'postcss-icss-values/lib/icss'>;
}
declare module 'postcss-icss-values/lib/index.js' {
  declare module.exports: $Exports<'postcss-icss-values/lib/index'>;
}
