export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const HIDE_SIDEBAR = 'HIDE_SIDEBAR';
export const HANDLE_RESIZE = 'HANDLE_RESIZE';

export const INIT_DASHBOARD = 'INIT_DASHBOARD';
export const SET_TIME_FRAME_DASHBOARD = 'SET_TIME_FRAME_DASHBOARD';
export const SET_TIME_FRAME_BREAK_EVEN = 'SET_TIME_FRAME_BREAK_EVEN';

export const SET_REVENUE_DASHBOARD = 'SET_REVENUE_DASHBOARD';
export const SET_REVENUE_BREAK_EVEN = 'SET_REVENUE_BREAK_EVEN';

export const SET_MONTHLY_COSTS = 'SET_MONTHLY_COSTS';
export const SET_COSTS_PER_TIME_FRAME = 'SET_COSTS_PER_TIME_FRAME';

export const CALCULATE_BREAK_EVEN = 'CALCULATE_BREAK_EVEN';
export const SET_BREAK_EVEN = 'SET_BREAK_EVEN';

export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';

export const LOADING = 'LOADING';
export const ERRORED = 'ERRORED';
export const FETCH_VENUES_SUCCESS = 'FETCH_VENUES_SUCCESS';
export const FETCHING_REVENUE = 'FETCHING_REVENUE';
export const FETCH_REVENUE_BREAK_EVEN_SUCCESS =
  'FETCH_REVENUE_BREAK_EVEN_SUCCESS';
export const FETCH_REVENUE_DASHBOARD_SUCCESS =
  'FETCH_REVENUE_DASHBOARD_SUCCESS';
export const FETCHING_INVOICES = 'FETCHING_INVOICES';
export const FETCH_INVOICES_SUCCESS = 'FETCH_INVOICES_SUCCESS';

export const IS_AUTHENTICATED = 'IS_AUTHENTICATED';
export const WRONG_CREDENTIALS = 'WRONG_CREDENTIALS';
export const CREDENTIALS_EXPIRED = 'CREDENTIALS_EXPIRED';

export const TOGGLE_NOTFICATION = 'TOGGLE_NOTFICATION';
